version:
  name: velociraptor
  version: 0.6.6-1
  commit: 41da5ef
  build_time: "2022-09-09T11:38:49Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3022106649
  compiler: go1.18.4
Client:
  server_urls:
  - https://{{servidor}}:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQIMZVbdfAaEXrXk2u0q3pijANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjIwOTIwMTczMTQxWhcNMzIw
    OTE3MTczMTQxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCr0RETgzcB9SXcFsyAa2KTNiSiAMAQKpY8
    7remdTV7v20PH3U92VurxTs5lsNu7rr9IBQMJtelZ9tS0NlMqxJRDz4s0x4brr4b
    /VQL+Y8Eyv48k4Uy/KqTObmCEbkQdG5KB6rGYorqitpIVF2YHPFdEq0fXuUr59fC
    ikhKbw2Sfeb3n0nA2pPGbk/kvPGQznFixOKoMCE/t5Z99KrCiEdLkxTE8SK/ghKZ
    9Gf2HWKIB/0bH0pOvbinFS5N2X/Hkk/1osssl3oZC5WaNwPDbr6wTeYPZ62WPXL/
    o76SYKjARVvxRmJsuw5N8vqNtLlXiZiLMWPE0N1kMr8lO3HMTmYbAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQeUSKeIa7zaX3MQOXfdyoE2v+r
    jjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAMMISVIOe793Y/CcBVElJucko7rpj25y+AjkWrGN2qGMh
    SW7zERQBwXZps0ZGmUz6BaxfpGzuzUElzk/Q19Mzwb/8eBmCgMlGC+OaEUvq2oWF
    7z132Wk+LQWDl34wVo6J3z+QgqOdOW+iuTxR/gJyIADzTUc686mt+cdMspzlFdaU
    xNlHRnsNkPPPznVWmROfp/Wa/Hi22yCTrWnUdJdLcgOzJj90sb3BfD9UuFUAmP2h
    iDkVQCRQ+InxDNICrGCZP5Z0xIxeVgf4tZ1v4zsvoge+8m9mCWC5ZXgkX4G63R/F
    rINLMlbqSRJug8m/9ufIClLqlRdwI95pcR/aB4fHAQ==
    -----END CERTIFICATE-----
  nonce: EJHCPuXti0o=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.6-1
    commit: 41da5ef
    build_time: "2022-09-09T11:38:49Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3022106649
    compiler: go1.18.4
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
