version:
  name: velociraptor
  version: 0.6.6-1
  commit: 41da5ef
  build_time: "2022-09-09T11:38:49Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3022106649
  compiler: go1.18.4
Client:
  server_urls:
  - https://{{IP}}:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQIMZVbdfAaEXrXk2u0q3pijANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjIwOTIwMTczMTQxWhcNMzIw
    OTE3MTczMTQxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCr0RETgzcB9SXcFsyAa2KTNiSiAMAQKpY8
    7remdTV7v20PH3U92VurxTs5lsNu7rr9IBQMJtelZ9tS0NlMqxJRDz4s0x4brr4b
    /VQL+Y8Eyv48k4Uy/KqTObmCEbkQdG5KB6rGYorqitpIVF2YHPFdEq0fXuUr59fC
    ikhKbw2Sfeb3n0nA2pPGbk/kvPGQznFixOKoMCE/t5Z99KrCiEdLkxTE8SK/ghKZ
    9Gf2HWKIB/0bH0pOvbinFS5N2X/Hkk/1osssl3oZC5WaNwPDbr6wTeYPZ62WPXL/
    o76SYKjARVvxRmJsuw5N8vqNtLlXiZiLMWPE0N1kMr8lO3HMTmYbAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQeUSKeIa7zaX3MQOXfdyoE2v+r
    jjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAMMISVIOe793Y/CcBVElJucko7rpj25y+AjkWrGN2qGMh
    SW7zERQBwXZps0ZGmUz6BaxfpGzuzUElzk/Q19Mzwb/8eBmCgMlGC+OaEUvq2oWF
    7z132Wk+LQWDl34wVo6J3z+QgqOdOW+iuTxR/gJyIADzTUc686mt+cdMspzlFdaU
    xNlHRnsNkPPPznVWmROfp/Wa/Hi22yCTrWnUdJdLcgOzJj90sb3BfD9UuFUAmP2h
    iDkVQCRQ+InxDNICrGCZP5Z0xIxeVgf4tZ1v4zsvoge+8m9mCWC5ZXgkX4G63R/F
    rINLMlbqSRJug8m/9ufIClLqlRdwI95pcR/aB4fHAQ==
    -----END CERTIFICATE-----
  nonce: EJHCPuXti0o=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.6-1
    commit: 41da5ef
    build_time: "2022-09-09T11:38:49Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3022106649
    compiler: go1.18.4
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  hostname: localhost
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: {{bind}}
  bind_port: 8889
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQjCCAiqgAwIBAgIRAKOa5tbx1fMxeXRpCW93wOEwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDkyMDE3MzE0MloXDTIz
    MDkyMDE3MzE0MlowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH
    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlV+WK4+qwQxz
    Tv5pOCIhMFXqqqBGbjMIM0YStPN+fRiDdS3FgZiShWGZnh8JszFxScrZzchQW3Y6
    1VaXq94reonWv7NZl94zT102wrXw4UVSAeGsBRxi681f60VNvncdsnnZku/nmO17
    A1UBgllCy2Y7Zna8ARSE+zYG1mAiWCDZquSCDPdl9J6FYIAwQugNXvslHHB9jK//
    3s+kRDgAiY9e3x1/hLkG8D/uXM7fBs4U7agbBNKdyx3/gkph/GPJeiXWk8qwH2HY
    MNxEOF8Wuxbi+CfN34iLJ77xEkbN+TEWNlWHl+zUNlhzR8MLanIr3itNCEEOnpbU
    LEpztCbZxwIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUHlEiniGu
    82l9zEDl33cqBNr/q44wEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF
    AAOCAQEAb68AeOj+y8yCcqsK2tYKHxhXuY4XBgScF/A8oGpuKiSlhuv7oXaC8J+b
    ICN/zrcBhPzc0IAiXbKFhZGswor+0RGwn6vxqAoVose0v0j64gDJ9r87ZRR7ownZ
    Xi1aSDXLxuR2OB1Fn0JoLhgeXOMCeqMBKWtv7l6fDfFmOVhTnvqi6Ih8X4wnI/pD
    YRLcJQIeVmjSHQ4rYeNIAHrv4EkO/nVAyWEe6rYeWsUn5SbCj3UVZLg6dzYXnhma
    IW3v6x/D/xhMV6YDvc4LwdCHUCz7zW/GihtEUhFjJkspzIQA5InI9NKDmdIk/5gf
    dU9QGmcE6etbgD/vpKe0dSuz3LJcnw==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAlV+WK4+qwQxzTv5pOCIhMFXqqqBGbjMIM0YStPN+fRiDdS3F
    gZiShWGZnh8JszFxScrZzchQW3Y61VaXq94reonWv7NZl94zT102wrXw4UVSAeGs
    BRxi681f60VNvncdsnnZku/nmO17A1UBgllCy2Y7Zna8ARSE+zYG1mAiWCDZquSC
    DPdl9J6FYIAwQugNXvslHHB9jK//3s+kRDgAiY9e3x1/hLkG8D/uXM7fBs4U7agb
    BNKdyx3/gkph/GPJeiXWk8qwH2HYMNxEOF8Wuxbi+CfN34iLJ77xEkbN+TEWNlWH
    l+zUNlhzR8MLanIr3itNCEEOnpbULEpztCbZxwIDAQABAoIBAGePnvDSqWMwe51v
    24lUeEgnuQvVFR9/+BZ8ZanZC4A1h6atNjrUifk5oqSzBimbhNzRa9I1KClRPhb8
    8yjwXpqViDLeaKZXIqHKkZXLSJcWVXYCfR4KATdU60SVhwIfWZKM0mECPUKUm23C
    +MnjkuCsH1C5zzy8ejokyfbFLeqExNtTIVEpGhOttEmgOyzmSx1N4UhPofEcVvI5
    s8Q7yWFkQ7IUoIOHUIBwP74K3FLp+019MUvOv0+8wFOUaD1Y42SeSFh20DrjKDm3
    w+7uFntJRoB+YoqepMLFOeK+YAFVIU2eK2BPn3zRZiIPAwrH9iS2PrL3Wo1ObMZA
    tSKmEoECgYEAwh4YZL+zNaXD3IZ1RuCcfABeCCytF64uUbROFDlgt9rJjABFR2a8
    ZYARBI/zysdMOkFq32KP6Uhrq8MZH9HvkJ9Yp5RIHr5ZcLPQWypGiTzJ3GpGx89K
    ROZ3IXik5S4IxIU/s6EKMkILrRXlcC5BvH2j/7I9OsGcS6M4KuuCwMECgYEAxP3t
    DcoPm/eSG8aYni8T8QpGmkSJGYWb5VUriNS6Ky5gpnz3RXx0vWKW4qSnDRJHrhwG
    KPwWAi+o5pr6OZBXeOx1+O8YxtZ4KcFpYh+5oaZ8NRaSAoOOjy0A0Q8+kDhqJp6x
    UenmBRisvcqp5TaG3o7eD3i4nqUK7adeimoMNIcCgYAb6df4JNjQThXsECmtF39p
    FWRwKHx7e0CN3y+bGOUfiwaQazmLGurcbZ4E2e5kqmP7vIxxsuqe0Rsqh9OFD9sz
    ILbO4jO8uAKEglbjxSB/e45Lc7zZ3qT/Y2SeG4saqZP5LnAKlI2yzGyBZzSm/P/W
    6vo6Opcza8Pd3IqnIVacAQKBgQC6i/Sm8Eij3GiioQj6E38A7kg54tkqMBqXrHYT
    l8/NAJhKUWEgjmFGz0wvyNjhSgRTXvp+aWq2G0gJSY3YYVZUjyiQ2mtOMN+OOzh+
    0ahK6owJAhy3ALpJ38Y8NAF9Nc9gTzuAZM2M2fcLrBYDmAVUUVr8r8e1hHm64Jpo
    3VA9lQKBgGW+cvtxe0Mb95+zdjrltSwThIfuMF4KFqNbIJ3K+IOKCBlqFMHtA4y4
    QcgphuSqRZ2wJDWArDqElMgyU1SmwL1lZ+8UaSDdg/D/oh2nieFuHdaepiRpF9+V
    fRNh3uYRDDnVNiVdbX7B39EyaXCxBgXkhXsxfg4KL3p3TiW9okzz
    -----END RSA PRIVATE KEY-----
  initial_users:
  - name: forense
    password_hash: 1e1ca3c66ebe84770da9d1a30e0c3ade018428eec6adf50da2d3cb86e9d32f8b
    password_salt: 06117f344cd57ebee7279fca150bed00fcd10139413a8d83ce17041b0b7b389f
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAq9ERE4M3AfUl3BbMgGtikzYkogDAECqWPO63pnU1e79tDx91
    Pdlbq8U7OZbDbu66/SAUDCbXpWfbUtDZTKsSUQ8+LNMeG66+G/1UC/mPBMr+PJOF
    Mvyqkzm5ghG5EHRuSgeqxmKK6oraSFRdmBzxXRKtH17lK+fXwopISm8Nkn3m959J
    wNqTxm5P5LzxkM5xYsTiqDAhP7eWffSqwohHS5MUxPEiv4ISmfRn9h1iiAf9Gx9K
    Tr24pxUuTdl/x5JP9aLLLJd6GQuVmjcDw26+sE3mD2etlj1y/6O+kmCowEVb8UZi
    bLsOTfL6jbS5V4mYizFjxNDdZDK/JTtxzE5mGwIDAQABAoIBAQCSGG16uAIYCgmt
    QT2WnLjvEATKM/UcSfoBycIjKlrV5ImpaEha1O2b+1NGvqljNF+PSK2DP6vyG4Nk
    we1jwbsLbfiiSMm7JDTGu/uxSvyPSMQxYgbKugmYsmbI8KT6FuaI0Egn9DbHBFZj
    VklXRJT/XRgUKq6XTMYrx0V89T0HJ95ixEbg/iZm5yarUlj0wkeXLS8JFj7avLpI
    lu2/BO8DcQQd0/6jOg+EsF2vCR9PYaicJsLQWfXE1p6rB7NZtbigS6rWfKO5E5OJ
    mVBDMSpO+p4WS3wChqD1QeXyH5G91xaA9ic+WUY2eXALQNKMvcoZpjVLWB1yvLoZ
    D8KXmPsBAoGBAMvDNYLcHMYg1M7ZsHJAKMF0+EiKs8n2mtt0hV+HV3a6EGOC0XQl
    qzH2LZcAlAQyDzywyrzIKsdA4R54UjB3H+iTpPw4SACAWfKJLopID2hNIKNVP8wY
    WXQlMmz0NqyZ+LxmI5/FQbsU36K/m2OqwO3SKBjKbGp+0DE+oXhnY+NbAoGBANfd
    Rd9h5J/lWxySgAOwHLICAkRdNNwscGGF7Iy9lLtl4KFxM5u24PsNH+ZJaujI3rj7
    uJqKKbIu9Ix8m3KgLtglDB4paMJF+q+7K0ms6BKgayK7JA6rDhGiOkmYxeJmHTGz
    9qFfpoIXVJCcMiuUESxY1qeOeZ0n8yqnrxk7oMRBAoGAQ2isHkOVXVJlNJ09yz5A
    fWel79G7Eth7eJh+uxC6NbPuUg1oH4WKsjef83GkhhLNiaVvHK8Xv91N3Fev0QrH
    yph1n187KrdLinoppGOcfUPuxTohpfJ0PYFEwli0cbtqV2Fu7Z9DVJHePignTvyh
    YMwCqdjlrwGO/IucvYluuTsCgYA3TJs6x6Q/Bg2aOzmKOFKRk4wrIUmKYeQER7+6
    qlJw03+BPDPBX08xYUJbx1EZA2RzNSEsjdpyqC7D0qQr8Dcv7gW1sFwC8NRwsl07
    iY0GQIxRoGlzTITVJZ8S/Y0sG4a9FeJHou5QA1QJm8oKeesQVk3fLNOg2/wiYESu
    DSV5QQKBgQCF+m9r/0HVIf5ucOTRLbcwkDtsjQgz9W1WPOnBV/41kbs3OrXRw9My
    Y8nvzhs3x8RiVZ+nMSpB5mOr5hU/mu6NBiA8Ciq7V1QlkjZTnxg5tgbNtDPVhaJK
    zbSusSbQmtkMpvuTkIVjg2T3aNTyvNogosZVhV5jem/GD8ltK0VrRA==
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: localhost
  bind_address: 0.0.0.0
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDWDCCAkCgAwIBAgIRAJA4ddNfb6CjvrzjAmYEXX0wDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDkyMDE3MzE0MVoXDTIz
    MDkyMDE3MzE0MVowNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW
    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDByH2YnZvv/MTkFdw5nUxK0Bao8mErZec/9f7vn9JQ4G8Z6AH2EHOXWdWklhKF
    NXSSpVNTcDIhf60g50Qu9YdJzc7GH5ereqLpg/mGEeomr4+Ezy7ATiNzsYSsJXyi
    dvzXAt2hY1aPb8AkyDKgDjM4VRBihWNXoKSI3VJLARTVrz0FGgbI3sfO6cu0/66R
    8VVffdvS1t1r3h9Z9UARDCkYhDFmmfZQoj334OVGRCsR/Tlq3QhhiJDk2LU0mq/+
    b8ZN1tVznx7fi6FlQRdQcc3pvZI0W3kbDBGOw+DHy7dfrCa5I0Fwn/sKemoTQj/P
    udo9W0Nf8C/arn2ytcV9pTUpAgMBAAGjfzB9MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSME
    GDAWgBQeUSKeIa7zaX3MQOXfdyoE2v+rjjAdBgNVHREEFjAUghJWZWxvY2lyYXB0
    b3JTZXJ2ZXIwDQYJKoZIhvcNAQELBQADggEBAKXs+g8a1J0aaGwK+5q98fCQXZzu
    CgfLCoD3ZnnBSjC9XOv6zWSSvuQdX4lhhU8dQD2o9+RhuQjJWXN7f57ehzBoRonC
    hOv70j0x/UWneu23dAVYfJ2qE6aRzkUwpvOrsMO32t9Ls8ItO/mCEE3geI0zun8U
    rZvxWTK8dt4Vc++5OF3aaGRd8z0wU6yNv/1wRG2um8PAg+vfs+Wr+x3UAPdCMHhX
    pcX18ovM6aqcJa0pTxkvA61+S9Gb40wjlYaXKZrWrmLw3KgqpyMDigNdiROiM4Qt
    pgN5Cw2Ngh2lsmuEi+Fv9i9gtiw7oMK/sSYFmtLmxHiWAsAW0h4EHtOJv+M=
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAwch9mJ2b7/zE5BXcOZ1MStAWqPJhK2XnP/X+75/SUOBvGegB
    9hBzl1nVpJYShTV0kqVTU3AyIX+tIOdELvWHSc3Oxh+Xq3qi6YP5hhHqJq+PhM8u
    wE4jc7GErCV8onb81wLdoWNWj2/AJMgyoA4zOFUQYoVjV6CkiN1SSwEU1a89BRoG
    yN7HzunLtP+ukfFVX33b0tbda94fWfVAEQwpGIQxZpn2UKI99+DlRkQrEf05at0I
    YYiQ5Ni1NJqv/m/GTdbVc58e34uhZUEXUHHN6b2SNFt5GwwRjsPgx8u3X6wmuSNB
    cJ/7CnpqE0I/z7naPVtDX/Av2q59srXFfaU1KQIDAQABAoIBADyqbI9rwBbIlkcl
    hNVQpkLBlGZ9wufYNiYy+AXCjhAdwwpkNMD484cNa7Hj/ZZQXtdOBKEZfcg49VVY
    sWLWIO19Dd++ojff48KhO2u6jghga9jTF7rCe5zLlVJjRfqCr7MMRaAxvjaXcJrT
    Re4Po/9dugxt3+Td+MSULSAoDYK7lwfNaGxd1fIvKq+Z+/ffEyXwO4nf4DxwolxS
    I0LxO9Kf9RaFGWBqqOLG7cful558EzYkBgjiEr+LfEKvrzt19HZkbuFvDc0yOQ+5
    lowsEtvIelQ9RuszwLkuJOikuvp+TuwkvHXya8ZYx5LPlTDWNaJWUwYsXheciZUf
    11GPFyUCgYEA09YIOS/oNNn+sgUxMjewAeyB5/PAmV+JviER2BvJAMPyxKRY6G/B
    FCZW7C8f37k5LWQC9nlwOfv91oBsdjpBSnik4kr2YKFS1/lhxeu1iQkoPqSrUBh8
    fldAeJiNiJ7qhYy8wsUX8d4gNQi6dIjB7tTq3uHTol5u7qJ8yVFCxZ8CgYEA6i7z
    p55zNR0Ok0uBIYGInzZNMysRzCkqqFtVFLhNxCzxQVszUVzRU2AfBZHQw2qWYh5Y
    DXpxG9VmUgfkfCHSk2LKZWEO3kHQpY/TAwNahTAZExGe7UZBUT/WYYYz6xwgDcWH
    Km0br2A6CpKuuURbDA39jtjuGIWcaeWxsuz7QDcCgYAM6OxTX+IM5oQpITvgTZiC
    ZYF9O1OvhS0F00odG4RicY6oAUQR1k20BqohdrXAkq8zXvb3QmtefUb4/ZaelepI
    uZWC3QKq3OoJk38r6rODiHVVa/+sv/FGWdbqApINk3HDddJDJHPTH7Biywdh9ruq
    7Hrr3mNhb9Pe4zQrqLIjDQKBgF2Ap6p6endvhZ1MHV/6b0lajhJrFO0WVsDnzp26
    RNqaMy2sM14+GBoZG+nGYbtUuHyuruuawsShPPxtyE3D12cfn75AtYYKcztXpKHk
    WeUp4ikZ9QG59mRxf7BqvBoYnbfB8YkADXjFjAcir/6rC0tR3raFaPODjYM+wee1
    9U+bAoGBAIPifOcbGnQdZzfIAo23XAvsDA5aqaaOiKrafBX1TpxRfhjDOUs8IdLu
    0woIi+0LAfJg5WyrAWqbT9CTM/x3vX51u20YJ0ZnqzbbvMT1Mfk2k6GgMhlr0EtM
    bUrYKCTgiY0W2qMiz6oaAElXNi4o6TeRAAw/4R61RoW1j+t1r5Eb
    -----END RSA PRIVATE KEY-----
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: /opt/velociraptor
  filestore_directory: /opt/velociraptor
Logging:
  output_directory: /opt/velociraptor/logs
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
server_type: linux
obfuscation_nonce: AO8XRuZ9TEw=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
