version:
  name: velociraptor
  version: 0.6.5
  commit: 5772dc32
  build_time: "2022-06-22T16:57:27+10:00"
  compiler: go1.18.1
Client:
  server_urls:
  - https://{{servidor}}:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRAKK9tbfJUbRK+ERTGsGWMa4wDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMTAxNDIyNDQzMloXDTMy
    MTAxMTIyNDQzMlowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3LgzOeASS6uB/jAnYN+Pb/4UX3TgS1is
    oa5eTMgauOnXs/xW3rUpABtYdXp4KW5N23wDF2szkMyuAdC0D7YZqmKMVxC1HkDT
    kQaPz5Eiq6ZIl06jV4jfNo23u08aLk8ZryrNzR+6EjeelNDuI2a3RZBkQTHnrCmn
    90rTBl1I34TmJHMu9eAjxPa0zMcr4dYfhQHsHopFsoOWMCrhMCUgqHq62TQP9zmg
    5lXPwh+l6wGgtJIo5VaSSzWJe7cp9C6nVh259J1jPaLnu5QEeLefDpTELO6E1W3f
    XOKS34BwPm1U5fQY5n6UCnUmSkUeNuCjTBpen9Lw/3VAheSHYRLcDQIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUfmDfVSu3TPLWLBkP83L1X8cM
    M9QwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBAGJWxkZ+pPJ+pbwG9hIU0FaCZTB6uukmUgm87TRtugRa
    GRATnJn9C4u3fAa2GNg/14jT529RwZCxLTQ2GG2KdnkaIyXWMwQre++YJKb8HEav
    adrtxi209rvNcvMEsMr5GmOzu9C3Mnwgw2kMdcMkVFngqQgQ7rZc2d/524ZOm4z2
    eNuvdgejU+F+z9fmG5wIHa+Xl6MOWMAplxUDo/pjaf3kAi1oZZ87raB6oAIg5o1H
    T3hR4zJ9dzYgJiP1wFQUlM0+vNFH2B6fNFGSDDVWUUpEvp2Mf5/yfi8O5La/7N2E
    yrKztsjCaRCc0uLhuYbeoWumSzMDtKF3sJHKwG8didU=
    -----END CERTIFICATE-----
  nonce: d1Lq5a/qjZ4=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.5
    commit: 5772dc32
    build_time: "2022-06-22T16:57:27+10:00"
    compiler: go1.18.1
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
