version:
  name: velociraptor
  version: 0.7.0-2
  commit: 82f2cad
  build_time: "2023-09-10T15:23:01Z"
  install_time: 1698090774
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/6137985901
  compiler: go1.21.0
Client:
  server_urls:
  - https://{{servidor}}:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQMxxMZjnYEv0HdLaHc2XjCjANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjMxMDIzMTk1NTUxWhcNMzMx
    MDIwMTk1NTUxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDPQBcdhpX9jn+9JJvPC0LCP8CQehAG9HzN
    mv+58kjFj5Gw6VxTFMo2p/3fMbXEd1WxCvA+9ZqIJJp1JfMFdXc7yndp9Ma+TrPj
    Vkj8nmxK4O5s+UAGHTCLVJ4FF4CBwYFgyJfRf7RssxDGEXP3Pi5D+/xQUkTabj6a
    rb5oQ56tPaK3F+TkzDeF+CaXO0WZE2lGhAmgCC7SRoyDL5oPw1WqaywUwpk2T+kz
    puCLrxL8+wYvt56caG0RtDa2avNxcXvnn3IYg+LyqsDOLj8+DIInPLT4aP01LgFL
    TWIkldKkoSMNUk5iI1oBZ5FUwwIJqXjJw91POEjbSRgfr1A8ui79AgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTHIrvQdnaObhj2JSmZTKYPAagr
    PjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEATJ0b8KjlprQgWk7Slke1TRtldxIju0ScoobMtnBaMQMk
    Rf/yqBnfUpBeeVW3lXvWI99mELnFUJrOimlQNKgHoRv4yeuhjrmRWRVw8O1WBBLi
    OQNPuQ5jyfwaS/KqivLwpcL9kAxwCcIATjVRg0ihTbAwjcD/cRSdXQQSdGaI+WqG
    mPbjUdSlzhxq6KHFKYaLgePQ5VgYv9fH5ce3QR5EzQTj7NHKh+b/yWWMgg0Vz0xI
    AyFcYyIkI5GhkqiNZncaUJP/KapQXSTNzb6ndvvsIp+OFebeRhAV2d7wWAndSl54
    AIdyI4o+HSw0Clu6e7KkpJx2TcTw/GPP8MyADAg+DQ==
    -----END CERTIFICATE-----
  nonce: Vn/6l9xAtRk=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.0-2
    commit: 82f2cad
    build_time: "2023-09-10T15:23:01Z"
    install_time: 1698090774
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/6137985901
    compiler: go1.21.0
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
